version: '3.8'
services:
  # Backend API (with .env.test)
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    container_name: nmt-app
    restart: always
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    env_file:
      - environments/.env.test
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules # ignore node_modules from local computer (take into account only inside of docker image)
    networks:
      - nmt-share_net

  # Test database (postgres)
  db:
    image: 'postgres:latest'
    container_name: nmt-db-test_container
    restart: always
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - environments/.env.test
    volumes:
      - './backups:/backups'
    networks:
      - nmt-share_net

  # Cache (Redis)
  redis:
    image: 'redis:latest'
    container_name: nmt-redis_container
    ports:
      - '6379:6379'
    networks:
      - nmt-share_net

networks:
  nmt-share_net:
    driver: bridge
